language: go
go: 
  - tip
sudo: false
before_install:
  - go get -u -v github.com/mattn/goveralls
install:
  - go get -t .
  - go get github.com/stretchr/testify
  - go get github.com/grokify/swaggman
  - go get github.com/grokify/swaggman/postman2
  - go get golang.org/x/oauth2
  - go get -u -v github.com/axw/gocov/gocov
  - go get golang.org/x/oauth2/google
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get gopkg.in/h2non/baloo.v3
  - go get github.com/nats-io/go-nats
script:  
  - goveralls -service=travis-ci
